routes/web.php
<?php

// use App\Repository\User\UserRepositoryInterface;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	return view('welcome');
});
// Route::get('user', function(UserRepositoryInterface $user) {
//     return $user->getUsers();
// });
// Route::get('user/{id}',function ($id,UserRepositoryInterface $user)
// {
//  return $user->findUser($id);
// });

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
	Route::resource('user', 'UserController');
	Route::resource('post', 'PostController');
	Route::resource('role', 'RoleController');
	Route::get('get-label', 'PostController@getLabel')->name('get_label');
});
Route::group(['prefix' => 'api'], function () {
	Route::post('user/store', 'UserController@store');
	Route::put('user/{id}', 'UserController@update');
	Route::delete('user/{id}', 'UserController@destroy');
});
// https://laravel.com/docs/5.4/migrations
Route::auth();

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Repository\User\UserRepositoryInterface;
use App\Role;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Request;

class UserController extends Controller
{
    protected $model;
    protected $requestName;
    protected $requestField;

    public function __construct()
    {
        $this->model = app(UserRepositoryInterface::class);
        $this->requestName = UserRequest::class;
        $this->requestField = ['name', 'email', 'password'];
        parent::__construct();
    }

    public function crudCallback($request)
    {
        //ada proses upload file
        $this->requestField = $request->has('password') ? ['name', 'email', 'password'] : ['name', 'email'];
    }

    public function callbackAfterCreateOrUpdate(User $model)
    {
        if (!Role::findOrFail(Request::input('role_id'))->user()->save($model)) {
            throw new Exception('Role attach fail', 1);
        }
    }

    // /**
    //  * mengoveride fungsi yang ada di parentnya.
    //  *
    //  * @return [type] [description]
    //  */
    // public function store()
    // {
    //     $request = app($this->getRequestName());
    //     if ($request->ajax()) {
    //         if (method_exists($this, 'crudCallback')) {
    //             $req = call_user_func_array([$this, 'crudCallback'], [$request]);
    //             if (!is_null($req) && $req instanceof Request) {
    //                 $request = $req;
    //             }
    //         }
    //         //make model or update model
    //         DB::beginTransaction();
    //         try {
    //             $model = $this->getModel()->insert($request->only($this->getRequestField()));
    //             if (method_exists($this, 'callbackAfterCreateOrUpdate')) {
    //                 $this->callbackAfterCreateOrUpdate($model);
    //             }
    //             DB::commit();

    //             return [
    //                 'message' => 'user berhasil di simpan',
    //                 'url' => route('admin.user.index'),
    //                 'type' => 'success',
    //             ];
    //         } catch (Exception $e) {
    //             DB::rollback();
    //             throw $e;
    //             return [
    //                 'message' => $e->getMessage(),
    //                 'type' => 'error',
    //             ];
    //         }
    //     }

    //     return parent::store();
    // }
}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('content')
	{!! Form::open(['route'=>"admin.{$module}.store",'method'=>'post','class'=>'form-horizontal','files'=>true,'id'=>'form-user']) !!}
		@include("{$module}.form")
		<div class="row">
			<div class="col-md-12 text-right">
				<button class="btn btn-primary submit">Create</button>
				<button class="btn btn-danger" type="reset">Reset</button>
			</div>
		</div>
	{!! Form::close() !!}
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('content')
	{!! Form::model($item,['route'=>["admin.{$module}.update",$item->id],'method'=>'PUT','class'=>'form-horizontal', 'id'=>'form-user']) !!}
		@include("{$module}.form")
		<div class="row">
			<div class="col-md-12 text-right">
				<button class="btn btn-info submit">Update</button>
				<button class="btn btn-danger" type="reset">Reset</button>
			</div>
		</div>
	{!! Form::close() !!}
@endsection

resources/views/user/form.blade.php
@inject('role', 'App\Role')
<div class="form-group" id="form-name">
	{!! Form::label("name","Name User",['class'=>'control-label'])!!}
    {!! Form::text('name',null,['placeholder'=>'Name User','class'=>'form-control','id'=>'name']) !!}                    
</div>
<div class="form-group" id="form-email">
	{!! Form::label("email","Email User",['class'=>'control-label'])!!}
	{!! Form::text('email',null,['placeholder'=>'Email User','class'=>'form-control','id'=>'email']) !!}                    
</div>
<div class="form-group" id="form-password">
	{!! Form::label("password","Password",['class'=>'control-label'])!!}
    {!! Form::password('password',['placeholder'=>'Password','class'=>'form-control','id'=>'password']) !!}                    
</div>
<div class="form-group">
	{!! Form::label("password_confirmation","Password Confirmed",['class'=>'control-label'])!!}
    {!! Form::password('password_confirmation',['placeholder'=>'Password Confirmed','class'=>'form-control','id'=>'password_confirmation']) !!}
</div>
<div class="form-group" id="form-role_id">
	{!! Form::label("role_id","Role",['class'=>'control-label'])!!}
    {!! Form::select('role_id',$role->pluck('title','id'),['placeholder'=>'Password Confirmed','class'=>'form-control','id'=>'role']) !!}
</div>

@push('javascript')
<script type="text/javascript">
	function submitForm(event) {
		event.stopPropagation();
		event.preventDefault();

		var form = $('#form-user'),
			urlForm = form.attr('action'),
			method  = form.find('input[name="_method"]').length > 0 ? 'update' : 'store';
			console.log("tes");
			$.ajax({
				url:urlForm,
				method:'POST',
				data:form.serialize(),
				success:function (data) {
					if(data.type === 'success'){
						alert(data.message)
						// if(confirm(data.message)){
							window.location.href = data.url;
						// }
					}else if (data.type === 'error'){
						alert(data.message);
					}
				},
				error:function (data) {
					//netralisir form dari error
					var form_all = $('div[id^="form-"]');
					form_all.find('span.help-block').remove();
					form_all.removeClass('has-error');

					//parse error dari server ke json
					jsonErrors = JSON.parse(data.responseText);

					//featch error dari server
					$.each(jsonErrors,function (field,errors) {

						//cari field yang error
						var element = $('#form-'+field);
						//tambahkan class error
						element.addClass('has-error');
						//featch semua error dalam 1 field
						
						$.each(errors,function (i,error) {

							// tampilkan pesan error dari server didalam div per field
							var message = $('<span>',{class:'help-block'}).text(error)
							element.append(message);
						});
					});
				}

			});
	}
	$(document).on('click','.submit',submitForm);
	$(document).on('submit','#form-user',submitForm);
</script>	
@endpush

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
	<table class="table table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Created At</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		@foreach ($items as $item)
			<tr>
				<td>{{ $item->name }}</td>
				<td>{{ $item->email }}</td>
				<td>{{ $item->created_at->format('d F Y') }}</td>
				<td>
					{!! Form::open(['route'=>['admin.user.destroy',$item->id],'method'=>'delete','class'=>'form-delete']) !!}
						<div class="btn-group">	
							<a class="btn btn-xs btn-info" href="{{ route('admin.user.edit',$item->id) }}">Edit</a>
							<a class="btn btn-xs btn-warning" href="{{ route('admin.user.show',$item->id) }}">View</a>	
							<button class="btn btn-xs btn-danger" type="submit"> Delete</button>
						</div>
					{!! Form::close() !!}
				</td>
			</tr>
		@endforeach
	</tbody>

</table>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')
@section('content')
	<a class="pull-right btn btn-default" href="{{ route("admin.{$module}.index") }}">Back</a>
	<br>
	<br>
	<table class="table table-bordered">
		<tbody>
			<tr>
				<td>User Name</td>
				<td>:</td>
				<td>{{ $item->name }}</td>
			</tr>
			<tr>
				<td>User Email</td>
				<td>:</td>
				<td>{{ $item->email }}</td>
			</tr>
			<tr>
				<td>User Role</td>
				<td>:</td>
				<td>{{ $item->role->title	 }}</td>
			</tr>
			<tr>
				<td>dibuat tanggal</td>
				<td>:</td>
				<td>{{ $item->created_at->format('m F y') }}</td>
			</tr>
		</tbody>
	</table>
@endsection